(defun lre-getbmp ()
  (interactive)
  (let ((all-string ""))
    (goto-char (point-min))
    (while (search-forward " start efi " nil t)
      (forward-char 1)
      (let ((p (point)))
	(search-forward "';")
	(forward-char -2)
	(setq all-string (concat all-string
				 (buffer-substring-no-properties p (point))
				 "\t")))
      (beginning-of-line 2)
      (forward-char 7)
      (let ((p (point)))
	(end-of-line)
	(forward-char -2)
	(setq all-string (concat all-string
				 (buffer-substring-no-properties p (point))
				 "\n"))))
    (set-buffer (get-buffer-create "*bitmaps ddf*"))
    (goto-char (point-max))
    (insert all-string)
    (sort-lines nil (point-min) (point-max))))
